sudo: false
language: node_js
node_js:
  - 14
cache: npm
install:
  - npm install
  - yarn install
branches:
    only:
    - master # build master branch only
script:
  - hexo g -d
deploy:
    provider: pages
    skip-cleanup: true
    github-token: ${{ secrets.GH_TOKEN }}
    keep-history: true
    on:
    branch: master
    local-dir: public