name: Deploy blog to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn --cwd "./"

      - name: Clean for blog
        run: yarn --cwd "./" clean

      - name: Build for blog
        run: yarn --cwd "./" build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: publish
          repository-name: Nthily/MyBlog
