name: Deploy blog to GitHub Pages

on:
  push:
    branches:
      - master  # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install
        run: 
          npm install
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: ./
          repository-name: Nthily/MyBlog
          
